apiVersion: v1
kind: Namespace
metadata:
  name: audio-monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sockops-tracer
  namespace: audio-monitor
spec:
  selector:
    matchLabels:
      name: sockops-tracer
  template:
    metadata:
      labels:
        name: sockops-tracer
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: sockops-tracer
        image: sockops-tracer:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_RESOURCE
            - CAP_BPF
            - CAP_PERFMON
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: false
        - name: output
          mountPath: /output
        - name: debugfs
          mountPath: /sys/kernel/debug
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: output
        hostPath:
          path: /tmp/ebpf-output
          type: DirectoryOrCreate
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      tolerations:
      - operator: Exists