apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: audio-latency-tracker
  namespace: audio-latency-tracker
  labels:
    app: audio-latency-tracker
spec:
  selector:
    matchLabels:
      app: audio-latency-tracker
  template:
    metadata:
      labels:
        app: audio-latency-tracker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: audio-latency-tracker
      hostNetwork: true
      hostPID: true
      containers:
      - name: audio-latency-tracker
        image: audio-latency-tracker:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - BPF
            - NET_ADMIN
            - SYS_ADMIN
            - NET_RAW
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: audio-latency-config
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: proc
          mountPath: /proc
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: bpf
          mountPath: /sys/fs/bpf
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: bpf
        hostPath:
          path: /sys/fs/bpf
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists